export const SET_AUTH_INFO = 'SET_AUTH_INFO';
export const CLEAR_AUTH_INFO = 'CLEAR_AUTH_INFO';
export const SET_AUTH_LOADING_STATUS = 'SET_AUTH_LOADING_STATUS';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const PUT_NEWS_LIST = 'PUT_NEWS_LIST';
export const SET_NEWS_LIST_LOADING_STATUS = 'SET_NEWS_LIST_LOADING_STATUS';
